import { bridge } from "./util.ts";
import type * as moduleType from "@codemirror/language";

const module = (await bridge("@codemirror/language")) as typeof moduleType;

export default module;

export const {
  DocInput,
  HighlightStyle,
  IndentContext,
  LRLanguage,
  Language,
  LanguageDescription,
  LanguageSupport,
  ParseContext,
  StreamLanguage,
  StringStream,
  TreeIndentContext,
  bidiIsolates,
  bracketMatching,
  bracketMatchingHandle,
  codeFolding,
  continuedIndent,
  defaultHighlightStyle,
  defineLanguageFacet,
  delimitedIndent,
  ensureSyntaxTree,
  flatIndent,
  foldAll,
  foldCode,
  foldEffect,
  foldGutter,
  foldInside,
  foldKeymap,
  foldNodeProp,
  foldService,
  foldState,
  foldable,
  foldedRanges,
  forceParsing,
  getIndentUnit,
  getIndentation,
  highlightingFor,
  indentNodeProp,
  indentOnInput,
  indentRange,
  indentService,
  indentString,
  indentUnit,
  language,
  languageDataProp,
  matchBrackets,
  sublanguageProp,
  syntaxHighlighting,
  syntaxParserRunning,
  syntaxTree,
  syntaxTreeAvailable,
  toggleFold,
  unfoldAll,
  unfoldCode,
  unfoldEffect,
} = module;
