import { bridge } from "./util.ts";
import type * as moduleType from "@codemirror/view";

const module = (await bridge("@codemirror/view")) as typeof moduleType;

export default module;

export const {
  BidiSpan,
  BlockInfo,
  BlockType,
  Decoration,
  Direction,
  EditorView,
  GutterMarker,
  MatchDecorator,
  RectangleMarker,
  ViewPlugin,
  ViewUpdate,
  WidgetType,
  closeHoverTooltips,
  crosshairCursor,
  drawSelection,
  dropCursor,
  getDrawSelectionConfig,
  getPanel,
  getTooltip,
  gutter,
  gutterLineClass,
  gutterWidgetClass,
  gutters,
  hasHoverTooltips,
  highlightActiveLine,
  highlightActiveLineGutter,
  highlightSpecialChars,
  highlightTrailingWhitespace,
  highlightWhitespace,
  hoverTooltip,
  keymap,
  layer,
  lineNumberMarkers,
  lineNumberWidgetMarker,
  lineNumbers,
  logException,
  panels,
  placeholder,
  rectangularSelection,
  repositionTooltips,
  runScopeHandlers,
  scrollPastEnd,
  showPanel,
  showTooltip,
  tooltips,
} = module;
